name: OriginsRebornTweaks
version: 1.0.0
main: com.starshooterstudios.ort.Main
description: Origins-Reborn addon
api-version: '1.19'
author: cometcake575

depend:
  - Origins-Reborn
  - Origins-Monsters
