name: Origins-Monsters
version: 1.0.0
main: com.starshootercity.OriginsMonsters
description: Origins-Reborn addon to add monster-themed origins
api-version: '1.20'
author: cometcake575

depend:
  - Origins-Reborn
