name: CometDevTools
version: 1.0.0
main: com.starshooterstudios.cometdevtools.CDTMain
description: Dev tools to help with plugin debugging
api-version: '1.21'

commands:
  item-data:
    usage: /<command>
    description: Get component data from held item
