name: CommandOnOriginSwapAddon
version: 1.0.0
main: com.starshootercity.originswapcommandaddon.Main
description: Origins-Reborn addon allowing you to run a command upon swapping origins
api-version: '1.19'
author: cometcake575

depend:
  - Origins-Reborn

softdepend:
  - Origins-Mobs
  - Origins-Monsters
  - Origins-Fantasy
